# Generated by Django 3.1.12 on 2025-05-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
